<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mac.alphionsee.in" failures="0" tests="7" name="testscript.LoginTest" time="15.936" errors="1" timestamp="2025-05-26T16:58:41 IST" skipped="3">
  <testcase classname="testscript.LoginTest" name="verifyUserLoginWithValidCredential" time="2.124">
    <error message="/Users/anumelbin/git/Grocery-application/Mainproject/src/test/resources/TestData (Is a directory)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: /Users/anumelbin/git/Grocery-application/Mainproject/src/test/resources/TestData (Is a directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:159)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
at utilities.ExcelReadUtility.readStringData(ExcelReadUtility.java:17)
at pages.LoginPage.loginByUsingUtility(LoginPage.java:52)
at testscript.LoginTest.verifyUserLoginWithValidCredential(LoginTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyUserLoginWithValidCredential -->
  <testcase classname="testscript.LoginTest" name="verifySigninWithValidUsernameAndInvalidPassword" time="3.617"/>
  <testcase classname="testscript.LoginTest" name="verifyUserLoginWithValidCredential" time="1.917">
    <skipped/>
  </testcase> <!-- verifyUserLoginWithValidCredential -->
  <testcase classname="testscript.LoginTest" name="verifyUserLoginWithValidCredential" time="2.083">
    <skipped/>
  </testcase> <!-- verifyUserLoginWithValidCredential -->
  <testcase classname="testscript.LoginTest" name="verifySigninWithInvalidCredentials" time="2.158"/>
  <testcase classname="testscript.LoginTest" name="verifyUserLoginWithValidCredential" time="1.943">
    <skipped/>
  </testcase> <!-- verifyUserLoginWithValidCredential -->
  <testcase classname="testscript.LoginTest" name="verifySigninWithInvalidUsernameAndValidPassword" time="2.094"/>
</testsuite> <!-- testscript.LoginTest -->
